Parse page
suhocki/starlord pull request #53
Opened 2019-03-27 10:41 UTC by pcfaktor

#41

2019-03-27 11:33 UTC, suhocki requested changes

2019-03-27 11:33 UTC, suhocki commented on app/src/main/java/kt/school/starlord/ui/global/CategoryAdapterDelegate.kt
> -            count.text = item.count.toString()
поправь вёрстку item_category.xml (удали textview "count")

2019-03-27 11:33 UTC, suhocki commented on app/src/main/java/kt/school/starlord/model/MockRepository.kt
> +        val parser = PageParser()
Не нужно менять внутренности MockRepository. Он задумывался для других целей - предоставлять тестовые данные. 

Создай NetworkRepository и реализуй в нём интерфейс CategoriesRepository. В новом репозитории данные бери уже через сеть

2019-03-27 14:00 UTC, suhocki requested changes

2019-03-27 14:00 UTC, suhocki commented on app/src/main/java/kt/school/starlord/model/MockRepository.kt
> +//            Category("Телефоны. Смартфоны", 249),
у категорий оставь только названия, числа удали

2019-03-27 14:00 UTC, suhocki commented on app/src/main/java/kt/school/starlord/model/NetworkRepository.kt
> +        return PageParser().allCategories
делегируй создание PageParser DI фреймворку
иначе такой код будет сложно протестировать с помощью юнит тестов

2019-03-27 14:00 UTC, suhocki commented on app/src/main/java/kt/school/starlord/domain/PageParser.kt
> +    private val urlConnection: HttpURLConnection = url.openConnection() as HttpURLConnection
Вынеси логику по загрузке данных в другой класс
тут оставь только метод, который принимает строку, парсит её и отдаёт полезные данные - список категорий

2019-04-18 12:47 UTC, suhocki requested changes

2019-04-18 12:47 UTC, suhocki commented on app/src/main/java/kt/school/starlord/di/PageParser.kt
> +    var allCategories: ArrayList<Category> = ArrayList()
```suggestion
    var allCategories: List<Category> = mutableListOf()
```

2019-04-18 12:47 UTC, suhocki commented on app/src/main/java/kt/school/starlord/di/PageParser.kt
> +    fun parsePage(loadedPage: String): ArrayList<Category> {
```suggestion
    fun parsePage(loadedPage: String): List<Category> {
```

2019-04-18 12:47 UTC, suhocki commented on app/src/main/java/kt/school/starlord/di/PageParser.kt
> +        val allData: Sequence<MatchResult> = Regex("""<h3>(.|\n)*?</div>""").findAll(loadedPage)
```suggestion
        val allData: Sequence<MatchResult> = """<h3>(.|\n)*?</div>""".toRegex().findAll(loadedPage)
```
исправить во всех местах
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-regex.html

2019-04-18 12:47 UTC, suhocki commented on app/src/main/java/kt/school/starlord/di/PageParser.kt
> +            val subCategories: ArrayList<Subcategory> = ArrayList()
```suggestion
            val subCategories = mutableListOf<Subcategory>()
```

2019-04-18 12:47 UTC, suhocki commented on app/src/main/java/kt/school/starlord/di/PageLoader.kt
> +package kt.school.starlord.di
класс PageLoader не может находиться в пакете di

в пакете di находятся лишь di модули, наподобие kt.school.starlord.di.categoriesModule
в модулях описывается то, каким образом будут провайдиться объекты (фактори или синглтон)
к примеру, вот законченный проект на базе koin и то, как располагаются файлы в папке di
https://github.com/Ekito/koin-samples/tree/master/samples/android-weatherapp-mvvm/app/src/main/kotlin/org/koin/sampleapp/di

перемести классы, не относящиеся к папке di в нужные папки
для того, чтобы лучше понимать структуру андроид проекта советую посмотреть эти ссылки
https://github.com/ImangazalievM/CleanArchitectureManifest#packages-organization
https://github.com/AndroidArchitecture/AndroidArchitectureBook/blob/master/practice/Practice_article.md
https://gitlab.com/terrakok/gitlab-client/tree/develop/app/src/main/java/ru/terrakok/gitlabclient

последняя ссылка - очень классный проект написанный недавно профи андроид разработчиками. У них папка di называется toothpick (в честь библиотеки, которую они используют для организации di)

если возникнут трудности, то можем подумать вместе. Давай отталкиваться от того, что в любом современном андроид-проекте есть ряд сущностей: 
1. view (фрагменты / активити)
2. viewmodel (презентеры / вьюмодели)
3. domain (интерфейсы для viewmodel)
4. model (репозитории)
5. data (различные источники информации)
6. di (создание объектов, подстановка нужных зависимостей при создании объектов)
7. entity (обычно kotlin data class)

Я предполагаю, что тебе нужно поместить свой класс в пункт 5 - data, так как это какой-то источник информации

2019-04-18 12:47 UTC, suhocki commented on app/src/main/java/kt/school/starlord/di/PageParser.kt
> +package kt.school.starlord.di
неверно выбран пакет. Парсер - источник данных, смотри коммент выше

2019-04-18 12:47 UTC, suhocki commented on app/src/main/java/kt/school/starlord/model/NetworkRepository.kt
> +        val page: String = PageLoader().page
создание объекта PageLoader делегируй di фреймворку

2019-04-26 11:08 UTC, pcfaktor commented
Видимо неправильно в CategoriesModule.kt

2019-05-03 08:53 UTC, suhocki requested changes

2019-05-03 08:53 UTC, suhocki commented on app/src/main/java/kt/school/starlord/model/NetworkRepository.kt
> +        val parser = PageParser()
если я вызову метод getCategories() 100 раз, то создастся 100 объектов PageParser
чтобы избежать лишнего выделения памяти, можно переиспользовать этот объект
поэтому вынеси его в конструктор и при помощи di внедряй как зависимость

2019-05-03 08:53 UTC, suhocki commented on app/src/main/java/kt/school/starlord/model/PageLoader.kt
> +            val page = urlConnection.inputStream.bufferedReader().readText()
```suggestion
            urlConnection.inputStream.bufferedReader().readText()
```

2019-05-03 08:53 UTC, suhocki commented on app/src/main/java/kt/school/starlord/model/PageLoader.kt
> +            page
```suggestion
```

2019-05-03 08:53 UTC, suhocki commented on app/src/main/java/kt/school/starlord/model/PageParser.kt
> +    var allCategories = mutableListOf<Category>()
что будет с коллекцией allCategories, если я вызову метод parsePage дважды? ответ - она будет содержать дубликаты. решение - не выносить что-либо в поле класса, в держать всё в рамках метода. Просто создай в методе parsePage эту коллекцию,а отсюда удали

2019-05-05 12:13 UTC, suhocki requested changes

2019-05-05 12:13 UTC, suhocki commented on app/src/main/java/kt/school/starlord/di/CategoriesModule.kt
> +    factory { PageLoader() }
PageLoader должен быть single, а не factory, потому что мы будем его наверняка переиспользовать на других экранах, где тоже нужно будет парсить html

2019-05-05 12:13 UTC, suhocki commented on app/src/main/java/kt/school/starlord/model/PageLoader.kt
> +        return try {
urlConnection имплементит AutoCloseable, поэтому переделай на try with resources

2019-05-13 08:28 UTC, suhocki requested changes
Смержись с девелопом, я там добавил codestyle проверки.

2019-05-13 08:28 UTC, suhocki commented on app/src/main/java/kt/school/starlord/model/PageLoader.kt
> +    private val urlConnection: HttpURLConnection = url.openConnection() as HttpURLConnection
перемести инициализацию urlConnection в метод, а переменную удали
дело в том, что url.openConnection() должен вызываться непосредственно перед отправкой сетевого запроса, по моему

UPD: Действительно. Иначе даже краш из-за того что обращение к urlConnection происходит после вызова close()
![image_2019-05-10_23-25-39](https://user-images.githubusercontent.com/14161040/57554919-6984e700-737b-11e9-9858-1501247246e8.png)

2019-05-14 06:38 UTC, suhocki approved these changes
LGTM

2019-05-14 07:09 UTC, merged