JSOUP parsing
suhocki/starlord pull request #66
Opened 2019-04-04 13:14 UTC by AMartsinkevich

#65

2019-04-04 14:28 UTC, suhocki commented
приаттачь к проекту starlord project

2019-04-05 05:30 UTC, AMartsinkevich commented
> приаттачь к проекту starlord project

Сразу не давало. Приаттачил-)

2019-04-18 12:54 UTC, suhocki reviewed
убери изменения во всех файлах в папках .idea
их быть не должно. Студия постоянно автоматически что-то в них меняет, но мы их не пушим.
Я подумаю как в будущем это исправить, чтобы эти файлы не трекались гитом

2019-04-18 20:34 UTC, suhocki requested changes
Подтяни изменения из девелопа

2019-04-18 20:34 UTC, suhocki commented on app/.idea/gradle.xml
> +        <option name="testRunner" value="PLATFORM" />
убери изменения во всех файлах в папках .idea
их быть не должно. Студия постоянно автоматически что-то в них меняет, но мы их не пушим.
Я подумаю как в будущем это исправить, чтобы эти файлы не трекались гитом

2019-04-18 20:34 UTC, suhocki commented on app/build.gradle.kts
> +
пустые строки не пушим

2019-04-18 20:34 UTC, suhocki commented on app/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.3-rc-2-all.zip
gradle пока не меняем

2019-07-13 07:24 UTC, closed without merging